spring:
  profiles:
    include:
      - graphql.playground
      - graphql.voyager
#  zipkin:
#    enabled: false
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    exampler:
      probability: 1
  application:
    name: FullExample
server:
  port: 8402
arc:
  dgraph:
    urls: localhost:9080